VGM2ZSM	= ./vgm2zsm
VGMS	:= $(wildcard ./ost/*.vgm)
ZSMR38	:= $(patsubst ./ost/%.vgm,./zsm38/%.zsm,$(VGMS))
ZSMR39	:= $(patsubst ./ost/%.vgm,./zsm39/%.zsm,$(VGMS))
ZSMS	:= $(ZSMR38) $(ZSMR39)

default: $(ZSMS)

.PHONY: $(ZSM2VGM)
$(VGM2ZSM):

.PHONY: %.zsm
%.zsm:	./zsm38/%.zsm ./zsm39/%.zsm

./zsm38/%.zsm: ./ost/%.vgm $(VGM2ZSM)
	$(VGM2ZSM) $< $@

./zsm39/%.zsm: ./ost/%.vgm $(VGM2ZSM)
	$(VGM2ZSM) $< $@
